package com.example.project.utils;

public class Cities {
    private String[] cities;

    public Cities() {
        this.cities = new String[]{
                "Warsaw","Kraków","Łódź","Wrocław","Gdańsk","Szczecin","Bydgoszcz","Lublin","Białystok",
                "Katowice",
                "Gdynia",
                "Częstochowa",
                "Radom",
                "Rzeszów",
                "Toruń",
                "Sosnowiec",
                "Gliwice",
                "Olsztyn",
                "Zabrze",
                "Bielsko-Biała",
                "Bytom",
                "Zielona Góra",
                "Rybnik",
                "Ruda Śląska",
                "Tychy",
                "Gorzów Wielkopolski",
                "Elbląg",
                "Dąbrowa Górnicza",
                "Płock",
                "Wałbrzych",
                "Włocławek",
                "Tarnów",
                "Chorzów",
                "Koszalin",
                "Kalisz",
                "Legnica",
                "Grudziądz",
                "Jaworzno",
                "Słupsk",
                "Jastrzębie Zdrój",
                "Nowy Sącz",
                "Jelenia Góra",
                "Siedlce",
                "Mysłowice",
                "Konin",
                "Piła",
                "Piotrków Trybunalski",
                "Lubin",
                "Inowrocław",
                "Ostrów Wielkopolski",
                "Suwałki",
                "Stargard",
                "Gniezno",
                "Ostrowiec Świętokrzyski",
                "Siemianowice Śląskie",
                "Głogów",
                "Pabianice",
                "Leszno",
                "Żory",
                "Zamość",
                "Pruszków",
                "Łomża",
                "Ełk",
                "Tarnowskie Góry",
                "Tomaszów Mazowiecki",
                "Chełm",
                "Mielec",
                "Kędzierzyn-Koźle",
                "Przemyśl",
                "Stalowa Wola",
                "Tczew",
                "Biała Podlaska",
                "Bełchatów",
                "Świdnica",
                "Będzin",
                "Zgierz",
                "Piekary Śląskie",
                "Racibórz",
                "Legionowo",
                "Ostrołęka",

        };
    }

    public String[] getCities() {
        return cities;
    }
}
